apiVersion: v1
kind: Service
metadata:
  name: echo-frontend
spec:
  clusterIP: 10.96.77.77
  ports:
  - name: tcp-echo-frontend
    port: 8080
    targetPort: 8080
  selector:
    app: echo-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-frontend
spec:
  replicas: 1
  template:
    metadata:
      name: echo-frontend
      labels:
        app: echo-frontend
    spec:
      nodeName: h1.meshinsight.meshbench-pg0.clemson.cloudlab.us
      containers:
      - image: xzhu0027/echo-frontend-grpc
        name: echo-frontend-grpc
  selector:
    matchLabels:
      app: echo-frontend