apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  clusterIP: 10.96.77.76
  ports:
  - name: tcp-echo-server
    port: 9000
    targetPort: 9000
  selector:
    app: echo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 1
  template:
    metadata:
      name: echo-server
      labels:
        app: echo-server
    spec:
      nodeName: h1.meshinsight.meshbench-pg0.clemson.cloudlab.us
      containers:
      - image: xzhu0027/echo-server-grpc
        name: echo-server-grpc
  selector:
    matchLabels:
      app: echo-server