apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: httpbin-wasm-filter
spec:
  selector:
    matchLabels:
      app: echo
  pluginName: add_header
  url: oci://webassemblyhub.io/ceposta/istioinaction-demo:1.0