# ISTIO 
PROTOCOLS:
  - TCP
  - HTTP
  - GRPC

REQUEST_SIZES:
  - 100
  - 1000
  - 2000
  - 3000
  - 4000

SIZES:
  TCP:
    R100:
      - 100
      - 241 
    R1000: 
      - 983
      - 1125
    R2000:
      - 1884
      - 2026
    R3000:
      - 2934
      - 3101
    R4000:
      - 3834
      - 4001
  HTTP:
    R100:
      - 100
      - 100
      - 252
      - 388
      - 388
      - 509 
    R1000: 
      - 983
      - 983
      - 1135
      - 1272
      - 1272 
      - 1393
    R2000:
      - 1884
      - 1884
      - 2036
      - 2197
      - 2197
      - 2312
    R3000:
      - 2934
      - 2934
      - 3086
      - 3248
      - 3248
      - 3362 
    R4000:
      - 3834 
      - 3834
      - 3986
      - 4148
      - 4148
      - 4262
  GRPC: 
    R100:
      - 134
      - 134
      - 160
      - 78
      - 78
      - 224 
    R1000: 
      - 1107
      - 1107
      - 1043
      - 961
      - 961 
      - 1107
    R2000:
      - 1917
      - 1917
      - 1943
      - 1861
      - 1861
      - 2007
    R3000:
      - 2967
      - 2967
      - 2993
      - 2911
      - 2911
      - 3057 
    R4000:
      - 3867 
      - 3867
      - 3893
      - 3811
      - 3811
      - 3957

ISTIO:
  LATENCY:
    PROXY:
      TCP: 
        IPC: process_backlog
        READ: vfs_readv
        WRITE: vfs_writev
        EPOLL: ep_send_events_proc
        USER: :*onReadReady*    
      HTTP: 
        IPC: process_backlog
        READ: vfs_readv
        WRITE: vfs_writev
        EPOLL: ep_send_events_proc
        USER: :*onReadReady*  
        PARSE: :*http_parser_execute*
      GRPC: 
        IPC: process_backlog
        READ: vfs_readv
        WRITE: vfs_writev
        EPOLL: ep_send_events_proc
        USER: :*onReadReady*  
        PARSE: :*nghttp2_session_mem_recv*
    APP:
      READ: vfs_read
      WRITE: vfs_write
      IPC: process_backlog
  CPU:
    PROXY:
      TCP: 
        IPC: br_handle_frame
        READ: Envoy::Network::IoSocketHandleImpl::readv
        WRITE: 
          - process_backlog
          - Envoy::Network::IoSocketHandleImpl::writev
        EPOLL: do_epoll_wait 
        USER: 
          - wrk:worker_0    
          - wrk:worker_1
      HTTP: 
        IPC: br_handle_frame
        READ: Envoy::Network::IoSocketHandleImpl::readv
        WRITE: 
          - process_backlog
          - Envoy::Network::IoSocketHandleImpl::writev
        EPOLL: do_epoll_wait 
        USER: 
          - wrk:worker_0    
          - wrk:worker_1
        PARSE: Envoy::Network::FilterManagerImpl::onContinueReading 
      GRPC: 
        IPC: br_handle_frame
        READ: Envoy::Network::IoSocketHandleImpl::readv
        WRITE: 
          - process_backlog
          - Envoy::Network::IoSocketHandleImpl::writev
        EPOLL: do_epoll_wait 
        USER: 
          - wrk:worker_0    
          - wrk:worker_1
        PARSE: Envoy::Network::FilterManagerImpl::onContinueReading 
    APP:
      READ: vfs_read
      WRITE: vfs_write
      IPC: process_backlog
    