# ISTIO 
PROTOCOLS:
  # - tcp
  # - http
  - grpc

REQUEST_SIZES:
  - 100
  # - 1000
  # - 2000
  # - 3000
  # - 4000

WRK_SCRIPT:
  TCP_PATH: benchmark/wrk_scripts/echo_workload/echo_workload_size.lua
  HTTP_PATH: benchmark/wrk_scripts/echo_workload/echo_workload_size.lua
  GRPC_PATH: benchmark/wrk_scripts/echo_workload_grpc/echo_workload_size.lua

ISTIO:
  LATENCY:
    PROXY:
      TCP: 
        IPC: process_backlog
        READ: vfs_readv
        WRITE: vfs_writev
        EPOLL: ep_send_events_proc
        USER: :*onReadReady*    
      HTTP: 
        IPC: process_backlog
        READ: vfs_readv
        WRITE: vfs_writev
        EPOLL: ep_send_events_proc
        USER: :*onReadReady*  
        PARSE: :*http_parser_execute*
      GRPC: 
        IPC: process_backlog
        READ: vfs_readv
        WRITE: vfs_writev
        EPOLL: ep_send_events_proc
        USER: :*onReadReady*  
        PARSE: :*nghttp2_session_mem_recv*
    APP:
      READ: vfs_read
      WRITE: vfs_write
      IPC: process_backlog
  CPU:
    PROXY:
      IPC: br_handle_frame
      READ: Envoy::Network::IoSocketHandleImpl::readv
      WRITE: 
          - process_backlog
          - Envoy::Network::IoSocketHandleImpl::writev
      EPOLL: do_epoll_wait 
      USER: 
        - wrk:worker_0    
        - wrk:worker_1
      PARSE: Envoy::Network::FilterManagerImpl::onContinueReading 
    APP:
      READ: vfs_read
      WRITE: vfs_write
      IPC: process_backlog

